apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: $dns
  namespace: default
spec:
  secretName: frontend-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: $dns
  dnsNames:
  - $dns