apiVersion: v1
kind: Service
metadata:
  name: front-end-service
spec:
  type: ClusterIP
  selector:
        project: front
        application: deploy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80